### ISSUE TITLE
The plugins `flutter_aes_ecb_pkcs5_fork, hexcolor` use a deprecated version of the Android embedding. 大哥有空更新下这个吧

### ISSUE THREAD

**Issue by WhiteCjy** [shareven/flutter_aes_ecb_pkcs5_fork#2]
The plugins `flutter_aes_ecb_pkcs5_fork, hexcolor` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by shareven** [comment]
Try to use the new version 0.1.4
