### ISSUE TITLE
不行啊这也

### ISSUE THREAD

**Issue by Xiaoqi-01** [shareven/flutter_aes_ecb_pkcs5_fork#3]
VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method generateDesKey on channel flutter_aes_ecb_pkcs5)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      FlutterAesEcbPkcs5.generateDesKey (package:flutter_aes_ecb_pkcs5_fork/flutter_aes_ecb_pkcs5_fork.dart:27:11)
<asynchronous suspension>
#2      _VideoDataState.downApkFunction (package:media_app/pages/video_data.dart:42:15)
<asynchronous suspension>

**Comment by shareven** [comment]
Try again , use version 0.1.4 , only support android and ios.
